### ISSUE TITLE
Linux下的有线设置

### ISSUE THREAD

**Issue by zxdawn** [Alrash/WebAuthenticate#3]
```
Traceback (most recent call last):
  File "webAuthenticate", line 242, in <module>
    if check_wifi_ssid() == False:
  File "webAuthenticate", line 125, in check_wifi_ssid
    iface = wifi.interfaces()[0]
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/pywifi/wifi.py", line 42, in interfaces
    for interface in wifi_ctrl.interfaces():
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/pywifi/_wifiutil_linux.py", line 248, in interfaces
    for f in os.listdir(CTRL_IFACE_DIR):
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/wpa_supplicant'
```
请问：在linux下运行，提示wpa_supplicant未找到。我已经安装了`wpasupplicant`，然而只有`wpa_passphrase`命令。
另外，我使用的是台式机(debian 9)，想开机自动连接inuist有线。

**Comment by Alrash** [comment]
这时因为这个程序是会首先连接wifi，这个错误的意思起始是无线报错

今天晚上10之后吧，我上传现在我用的版本，新上传的版本可以绕过这个问题

**Comment by Alrash** [comment]
@zxdawn

**Comment by zxdawn** [comment]
@Alrash 多谢！刚刚搜到了另一个[方法](https://blog.csdn.net/shenhuaifeng/article/details/78333851)，晚上我也试试。

**Comment by Alrash** [comment]
@zxdawn 你可以直接试试他的，刨去wifi自动连接部分，我的东西和他差不多╮(￣▽￣)╭

**Comment by zxdawn** [comment]
@Alrash 恩，试了下，可以的，哈哈。

**Comment by PROGRAMMERNO** [comment]
大佬知道怎么用路由器把有线网共享下嘛
